# Generated by Django 3.1.4 on 2020-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('NIEZNAM', 'Nie znam'), ('KOJARZE', 'Kojarzę'), ('ZNAM', 'Znam')], default='NIEZNAM', max_length=255)),
            ],
        ),
    ]
