# Generated by Django 3.1.5 on 2021-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0002_auto_20201207_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('NIEZNAM', 'Nie znam'), ('KOJARZE', 'Kojarzę'), ('ZNAM', 'Znam')], default='NIEZNAM', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_en',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
