# Generated by Django 3.1.5 on 2021-03-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0003_auto_20210227_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('BRAK', 'Nie wybrano'), ('NIEZNAM', 'Nie znam'), ('KOJARZE', 'Kojarzę'), ('ZNAM', 'Znam')], default=None, max_length=255, null=True),
        ),
    ]
