# Generated by Django 3.0.6 on 2021-03-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='status',
        ),
        migrations.CreateModel(
            name='ProfileWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BRAK', 'Nie wybrano'), ('NIEZNAM', 'Nie znam'), ('KOJARZE', 'Kojarzę'), ('ZNAM', 'Znam')], default=None, max_length=255, null=True)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wordapi.Profile')),
                ('word', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wordapi.Word')),
            ],
        ),
    ]
