# Generated by Django 3.0.6 on 2021-03-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0006_auto_20210304_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='_profile_words_+', to='wordapi.ProfileWord'),
        ),
        migrations.RemoveField(
            model_name='profileword',
            name='profile',
        ),
        migrations.AddField(
            model_name='profileword',
            name='profile',
            field=models.ManyToManyField(blank=True, related_name='_profileword_profile_+', to='wordapi.Profile'),
        ),
    ]
