# Generated by Django 3.0.6 on 2021-03-04 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0007_auto_20210304_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileword',
            name='profile',
            field=models.ManyToManyField(related_name='_profileword_profile_+', to='wordapi.Profile'),
        ),
        migrations.AlterField(
            model_name='profileword',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wordapi.Word'),
        ),
    ]
