# Generated by Django 3.0.6 on 2021-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0009_auto_20210304_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileword',
            name='profile',
        ),
        migrations.AddField(
            model_name='profileword',
            name='owner',
            field=models.ManyToManyField(related_name='_profileword_owner_+', to='wordapi.Profile'),
        ),
    ]
