# Generated by Django 3.0.6 on 2021-03-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0010_auto_20210304_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileword',
            name='owner',
        ),
        migrations.AddField(
            model_name='profileword',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wordapi.Profile'),
        ),
    ]
