# Generated by Django 3.0.6 on 2021-03-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0011_auto_20210304_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileword',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wordapi.Profile'),
        ),
    ]
