# Generated by Django 3.0.6 on 2021-03-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0012_auto_20210304_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileword',
            name='word_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wordapi.Word'),
        ),
    ]
