# Generated by Django 3.0.6 on 2021-03-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapi', '0013_auto_20210304_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileword',
            options={'ordering': ['-status']},
        ),
        migrations.AddField(
            model_name='word',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
